language: node_js
sudo: false
cache: yarn
node_js: 10.12
git:
  depth: 2
script:
- yarn lint
- yarn test:unit
- yarn test:e2e:headless
- yarn build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  on:
    tags: true
    branch: master
  github_token:
    secure: fb83uAg31qMGBAaEVGh4+7xySHRkYfNMeG/dHTmzlGXlUpXXiIr6cUhjia3dGhhrnVGWyEtt1IaV/PLjhRiyVmO5XQ3103xRhGgdmDCc+KcGy1cG1D0UcHHSJFIUWBqAHTTbXwr99inAYz9tYaEQT24bW2DdSodmpIQIV3GVgdz2VV1PJu1SW0ST/DvXxhWjHJxR9pVIUmQLPbp+A3VAPaN4flTUu/ZWI3gg5MtBtkgeErIMBYWjfUlKbStPKPfYXstOQq/Kl4HONoaMlYq/p5elToSoLTR+7JVXizAglATk2fr8UBGg9JEmxy9jcwYkVme1Z5l7JjvwLQEQSkt8lhGbaCQsLfoToT22o9S2NhjQdy3HzyR5Guyg1JRhO0kilYC1NDEvGmgm3FAJ3Au+Euf9qm8i0U0Et08QmXn1BahtiBugQLq0wBuMppvphmXiOgoQqtZoyWmzhCnJJFkHtOTxokPV3VTDFp2QbGjrhPqzNA+HftFAv320dT+vtcBAUOvVZbXoo0gIrN9/ScvQPk7u6/SQVu4iAcVdUjnRe5sz1wTBYPQYQjKwqqAsFmlZ/jerr/jEV5ji9ep/P0IwS4PW/e9SP0VEGLp/yMtj7RTk7XtA1HosC8OswwdRJZllhYzF6f+SxQutBKdXYXtTVNJxbHX3g5FfXgr0yCeCLFc=
