language: node_js
sudo: false
cache: yarn
node_js: 10.12
git:
  depth: 2
script:
- yarn lint
- yarn test:unit
- yarn build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token:
    secure: "JqvTdsO5mBk4uWzeMa1sZ1I779XwIx/+OOGY+9XPm177fwoqrfZIUhYPCT9VgWZPi6Aj8Nn0S0sISbF9hIEYKycGTEJZS0BFT1jIax3UA09hH+h4T5+8BBlQni+xD8NlrsXgpcoX8nqs2k0n2Sx0Y8dFp0Rqz1Kh8RdPHf5aApphAEcJhnZtK+NpsnCGVHRIMnqtjEsYLdUI0vx3crQulsx1UnaqO2KwvV4AfpHkO7+1+Y/JzchIa9fg6TeaFU363GHxl9AhKy3KUV7wN+eGpV31S37oSRBEn//HcpaXEfFQT1y5XGU8lTHmh7xTUL9hpnZO1Wkb/4mxON8EEEXBmJaZTnz5qVpzrkwvVprpVt5VJ9Gd7jSs1+WyaokdBlL4gtWEV9l6yd5XYzQRfizk5dbCbr3/DllwlNX9EjIfdx9rP/4nQihue5P7u6GReie4QvVMvfAAjRqHPg8JvDug3g3VnWMVok+AGJr45IrsLlrt476QcK6p5ifpWNa+bsE5sgoU2SSAxYnWBPFfjIQAbkEwUzuB0oFREtzdwByM+2da40Hr3vfdNcxndMMkLxCdxzKxaSmGamV5L++euoWLxnzlxLCiD3DYTuzBykcQ3fEZT+bLNvTV1ozKaSpKc94Y1O3pmxSjsiuTxQ9lfpO0TiymUvthcnE0Jq5yQ1hCHmM="
  on:
    tags: true
    branch: master
