language: node_js
sudo: false
cache: yarn
node_js: 10.12
git:
  depth: 2
script:
- yarn lint
- yarn test:unit
- yarn build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    tags: true
    branch: master
env:
  global:
    secure: 7DrlCkc3ucBZsxUS2QIhSItX6uCXsfDp6CHL1V52JUfNSEZ15mfJUdu0r0q9IOJ1Y5ghSP543KmyCRHG1UdCq0U23m8PmIEVWHwLcWmKi/TKQ4GiMByV9Sxxbd9Jxm85BHLJVcMWFjfRPeeSJbHfsDY7bXxRwdUOL7cZHBiTNLpDTm4CNpSlWMYOOAGAfygtocfEUfEu3+lzmZW2L1769lDxSmRIomFX4eq3AqM40djxjwAPaEbkwaXpO01wY6fTxWrCWT6rmmxV8+C/V8fZqdp35e5mCACNzYF5YS43Y9W2haON71Tly1SfPca/zt+fhCvChOJRnBpYrNMpHn3/+S0Ko3pLPNgco7wGBpU6613xsriLvRsMA0vox6TLFOhRCneVn4Q+6HqrkUu8nV/yFGKzAev2GevdcHU1Se7YfIty/Qjfz1p53JbrsIkLovfo5JEZlyr2odbqaueo1cs8JiyWr4APnumIee47NSVpSrFu/+AIptSMt865nnbyWMdniyRyn+EywcKbFApEhbs/1/evnZRFbUmebbxfV/MikxbiLSVfNPOEYkdvicWT7Y1DRNBilQOD4OmS/XE6BIjd/2+AVQ2uFCPfhwitGzmOs+PRd9RIbn8EY9CB0GRAVY1tZLnmxC4fdDg2DoGFN6JhyzJhhWjDRdBOQo+6T6y7l5Q=
