language: node_js
sudo: false
cache: yarn
node_js: 10.12
git:
  depth: 2
script:
- yarn lint
- yarn test:unit
- yarn build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token:
    secure: 5JPF3kTk+hBek0Kh0b78ewblADnsNmcmyBkgs0RGnFHAre1CpTcTL/4WFnhUJyPjmO8inUw4NJmZzKGSqz7EBAk4NpQaBE+X4Fq0cgzuZiKBSjDL9dCP7J0S17QAefgQXljFGV37Z7G1PyUOq/LC9B3i4UZxgJnHy9nCUz+HruhfDRfwLBIsPSur5sWySnqdqQpT+zdvg2NNVh3dz8Y78LeM1mFoYCVMT+/1W0i4FrgHajFYRM4GfUwWV6fwE5AyjWsqnpfEVpdKXpeCQXPJRwdqfMIbwHKxnn2w9ENmFIpb6VVGdRmhYtE3AbUiDEkQTAPr+aM5DSx2uJu/jR3UmBLT4fvHkK3k4njZBYQSY9Bh5eVn8j9bcAgiOHdN6xTsgJKFfU76z8yYCKZHENEQRRAF7hxdzeXz3EJXYi4aSK0lI/C1Lmlu1OE0gCUkoabhRqjTxrKkfBzQBDvINc53OWQoIJ2DhajFO/f2MvQ7hLoQiBEUYE+LS9Z/+x2l1hvF+iebnNau6W842+KbVtyU2OoBZ/pvU/XIl/MVwzWqdvsJ4QgKMNbMOTF2H2qTEgkBGH34FAppj3kPFmbkQBY9e6cdotHNbh+o1+j7hgjTZg9xnVT81CjgNUyBVgb75l7TMTyvRdyHuf1ZA/YinW+CMdAhCY8iF2H1JT1R0wUZiGk=
  on:
    tags: true
    branch: master
