language: node_js
sudo: false
cache: yarn
node_js: 10.12
git:
  depth: 2
script:
- yarn lint
- yarn test:unit
- yarn build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token:
    secure: GKqiYa/tr8wx+MEMqz5QV2e0lEkmUWOf7xff/WLsBNuF1oz7jryGuYTb2pvKB473+Xra/QUYCNr1gP7MWRHjB4oCyVy8HyHONxQdcz0ygINDgettqYPg6OnXGKR5S1m0PFGfc3gWh0pPGDxInRH8TMIpoLgoFDrRS+4g0YYRawdo2jLvKXK1LpXaqQO3rqWWCPDerUHJebwqZRnfwsshh/JA/tvRdiFtyaBF69I9EzxzD/qyNwyROd5lBI2vzWMEo3d0mAWitwujkmaBKpD8Mj5cyu/ab20sUMDnbmIbeIxtsvUXULWnNJMkXuxcFWW0AQlz8v1QLyw8uWeySuw7HkE2jeeCic5J+iOjFrHZcL0nR8tYlvHjR7cuJGY0rWNZxKzjoLKu7PZlr/kviutykW7z5NcUgkd9i7pycq4BTiu18Izf10Zzqm9RF1sovelT/wyBQUAc4zRQj/FMBKIdjPGu7PN2H3+TWVY7SWeTXrABSmN0h9ygXMLcb5QPb37mbV/tFj8ZaTDV1dKoMYus0CahU3iNgPKCYd/DknrrdzEHDJyGAQJiRmRhrWAG7ATwTzUMR2yZZ4kFYQK6iR72Nd0SHSt92T38h0TG21bBsa4v2cAyPCc/eVdjm2hfr32TgLosCfYavpal67ASg5NOxBR5IfJZG5T95u35LnN/IaM=
  on:
    tags: true
    branch: master
