language: node_js
sudo: false
cache: yarn
node_js: 10.12
git:
  depth: 2
script:
- yarn lint
- yarn test:unit
- yarn build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token:
    secure: rmNZQ9kFvveBGxHdWrgk2w8qiliN3urnal87E2FOTIDEyqDDCOyT7P+E5yFaf+jyfnO7TewzHiuVapXRoi61EJXchM1h99kYKLUeeExqSblIMf3poN/8WolSa1MSc90ZJpupR5BmqRPgMcdU93t0wX+jDWxoIsy3jZTuK40EXrrnwHN5vcTWAD1R02poduFp1fkhMKmjf7H1/qe2eK9URqPoSFY5xyTBI7nru3hP65e4MfMDyrGYAEl8vVPOaXFrDimJ6lOUvJPtM3wSipZVLNxigp9ev3wkmR8KChzXV0GBbUemBOSLng0qRZPJNujZxWyqZ3sFiuCZbWm5UEYzCNiZIy/e8u2WCzDkU74akbPg2yUG/I8DwFFLTAjfbYtmHXICy5fJ+AxOfjctFqNsXPqiwSjoqxYr+XG5p93jSH8toFG7bgik9oLZZ0Aii9VPoYQHHIKZNVjr+XOxzhleL1sR0nMSHiOc9EUqEORWQAAbfpNrvLbatXJmU+zAXJvwuCphCYYqpaMrJiOILDrq9+8FhCxR1kw+pQr5fWO9MwgEW1paVfRuH5NjzGJ7wGLTmpOP7E1v6VKg/LVOrB1goYdHlkBq943t0clgMRGymkW79edSgo7TE4qaTc5zlx8PY344qcAuHZ8UgnVkBfN0vflSSjXcbD/0YwQsfah59Pc=
  on:
    tags: true
    branch: master
